services:
  app:
    container_name: hobbyroom
    build:
      context: .
      dockerfile: Dockerfile
    image: hobbyroom:local
    command: "uvicorn hobbyroom.app.main:app --host 0.0.0.0 --port 9000 --reload --proxy-headers"
    environment:
      - APP_ENV=local
    volumes:
      - ./:/app
    expose:
      - 9000
    restart: unless-stopped 

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
