services:
  app:
    container_name: hobbyroom
    build:
      context: .
      dockerfile: Dockerfile
    image: hobbyroom:local
    command: sh -c "alembic upgrade head && uvicorn hobbyroom.app.main:app --host 0.0.0.0 --port 9000 --reload --proxy-headers"
    environment:
      - APP_ENV=local
    volumes:
      - ./:/app
    expose:
      - 9000
    restart: unless-stopped
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  
  db:
    container_name: hobbyroom_db
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db:
