"""apply custom pk to affiliation

Revision ID: 4f608e31a82f
Revises: 566ef4f0e418
Create Date: 2025-07-28 16:38:30.027401+00:00

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f608e31a82f"
down_revision: Union[str, Sequence[str], None] = "566ef4f0e418"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_persona_gathering", "affiliation", ["persona_id", "gathering_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_persona_gathering", "affiliation", type_="unique")
    # ### end Alembic commands ###
