"""remove affiliation id

Revision ID: 566ef4f0e418
Revises: 02d7cc38fb31
Create Date: 2025-07-26 15:20:58.145547+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "566ef4f0e418"
down_revision: Union[str, Sequence[str], None] = "02d7cc38fb31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("affiliation", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "affiliation", sa.Column("id", sa.UUID(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
